### ISSUE TITLE
Can't use swift-ring-builder command to view builder file for storage policy created on crystal controller.

### ISSUE THREAD

**Issue by xietiangui** [Crystal-SDS/Crystal-Controller#4]
I use the Crystal Controller to create a storage policy , when I use the swift-ring-builder command to view the builder file information, the error message is：
```
Traceback (most recent call last):
  File "/usr/bin/swift-ring-builder", line 24, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 1483, in main
    getattr(Commands, command, Commands.unknown)()
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 527, in default
    print_dev_f(dev, balance_per_dev[dev['id']], flags)
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 423, in print_dev_f
    print(format_string % args)
TypeError: %d format: a number is required, not str
```

**Comment by JosepSampe** [comment]
Hi @xietiangui, there was an issue creating the ring by the controllorer. The device port was stored as string and it must be integer. It is now solved with the last commit. Thanks for reporting.
